// class PassingDetails {
//   int productId, priceListId, createUserId, salesDetailsID, detailID, actualProductTaxID, productTaxID,exciseTaxID;
//   String productName,
//       quantity,
//       exciseTaxName,
//       bPValue,
//       exciseTaxBefore,
//       exciseTaxAfter,
//       unitPrice,
//       netAmount,
//       uniqueId,
//       exciseTaxAmount,
//       flavourID,
//       flavourName,
//       discountAmount,
//       grossAmount,
//       rateWithTax,
//       status,
//       costPerPrice,
//       discountPercentage,
//       taxableAmount,
//       vatPer,
//       vatAmount,
//       sgsPer,
//       sgsAmount,
//       cgsPer,
//       cgsAmount,
//       roundedUnitPrice,
//       netAmountRounded,
//       igsPer,
//       igsAmount,
//       roundedQuantity,
//       inclusivePrice,
//       unitPriceName,
//       additionalDiscount,
//       gstPer,
//       actualProductTaxName,
//       salesPrice,
//       totalTaxRounded,
//       description,
//       productTaxName;
//   bool productInc,  isAmountTaxAfter,  isAmountTaxBefore,
//       isExciseProduct;
//
//   PassingDetails({
//     required this.uniqueId,
//     required this.productName,
//     required this.grossAmount,
//     required this.unitPrice,
//     required this.exciseTaxAmount,
//     required this.netAmount,
//     required this.salesDetailsID,
//     required this.quantity,
//     required this.discountAmount,
//     required this.productId,
//     required this.rateWithTax,
//     required this.costPerPrice,
//     required this.priceListId,
//     required this.additionalDiscount,
//     required this.discountPercentage,
//     required this.isAmountTaxBefore,
//     required this.taxableAmount,
//     required this.vatPer,
//     required this.vatAmount,
//     required this.sgsPer,
//     required this.cgsAmount,
//     required this.cgsPer,
//     required this.createUserId,
//     required this.flavourID,
//     required this.flavourName,
//     required this.igsAmount,
//     required this.igsPer,
//     required this.sgsAmount,
//     required this.netAmountRounded,
//     required this.detailID,
//     required this.status,
//     required this.inclusivePrice,
//     required this.roundedUnitPrice,
//     required this.roundedQuantity,
//     required this.gstPer,
//     required this.unitPriceName,
//     required this.productTaxID,
//     required this.productTaxName,
//     required this.actualProductTaxName,
//     required this.actualProductTaxID,
//     required this.salesPrice,
//     required this.productInc,
//     required this.totalTaxRounded,
//     required this.description,
//     required this.exciseTaxID,
//     required this.exciseTaxName,
//     required this.bPValue,
//     required this.exciseTaxBefore,
//     required this.isAmountTaxAfter,
//     required this.isExciseProduct,
//     required this.exciseTaxAfter,
//   });
//
//   factory PassingDetails.fromJson(Map<dynamic, dynamic> json) {
//     return PassingDetails(
//       uniqueId: json['id'],
//       productId: json['ProductID'],
//       productName: json['ProductName'],
//       quantity: json['Qty'].toString(),
//       unitPrice: json['UnitPrice'].toString(),
//       description: json['Description'] ?? "",
//       rateWithTax: json['RateWithTax'].toString(),
//       costPerPrice: json['CostPerPrice'].toString(),
//       exciseTaxAmount: json['ExciseTax'].toString(),
//       grossAmount: json['GrossAmount'].toString(),
//       netAmount: json['NetAmount'].toString(),
//       priceListId: json['PriceListID'],
//       discountPercentage: json['DiscountPerc'].toString(),
//       discountAmount: json['DiscountAmount'].toString(),
//       taxableAmount: json['TaxableAmount'].toString(),
//       vatPer: json['VATPerc'].toString(),
//       vatAmount: json['VATAmount'].toString(),
//       salesDetailsID: json['SalesDetailsID'],
//       sgsPer: json['SGSTPerc'].toString(),
//       sgsAmount: json['SGSTAmount'].toString(),
//       cgsPer: json['CGSTPerc'].toString(),
//       cgsAmount: json['CGSTAmount'].toString(),
//       igsPer: json['IGSTPerc'].toString(),
//       igsAmount: json['IGSTAmount'].toString(),
//       additionalDiscount: json['AddlDiscAmt'].toString(),
//       createUserId: json['CreatedUserID'],
//       detailID: json['detailID'],
//       productInc: json['is_inclusive'],
//       roundedUnitPrice: json['unitPriceRounded'].toString(),
//       roundedQuantity: json['quantityRounded'].toString(),
//       inclusivePrice: json['InclusivePrice'].toString(),
//       netAmountRounded: json['netAmountRounded'].toString(),
//       unitPriceName: json['UnitName'],
//       gstPer: json['gstPer'].toString(),
//       productTaxName: json['ProductTaxName'],
//       flavourID: json['flavour'] ?? "",
//       flavourName: json['Flavour_Name'] ?? "",
//       productTaxID: json['ProductTaxID'],
//       status: json['Status'],
//       actualProductTaxName: json['ActualProductTaxName'],
//       actualProductTaxID: json['ActualProductTaxID'],
//       salesPrice: json['SalesPrice'].toString(),
//       totalTaxRounded: json['TotalTaxRounded'].toString(),
//       exciseTaxID: json['ExciseTaxID']??0,
//       exciseTaxName: json['ExciseTaxName'].toString(),
//       bPValue: json['BPValue'].toString(),
//       exciseTaxBefore: json['ExciseTaxBefore'].toString(),
//       isAmountTaxAfter: json['IsAmountTaxAfter']??false,
//       isExciseProduct: json['IsExciseProduct']??false,
//       isAmountTaxBefore: json['IsAmountTaxBefore']??false,
//       exciseTaxAfter: json['ExciseTaxAfter'].toString(),
//
//     );
//   }
// }